name: test worklow
on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: echo "hello"
            - name: Print goodbye
              run: echo "bye"





